import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
    	<body className='flex flex-col bg-[#fff] min-h-[100vh] pt-20'>
			  	<main>
            {children}
			  	</main>
    	</body>
    </html>
  )
}
